services:
  - type: web
    name: ecommerce-cart
    env: python
    buildCommand: |
      pip install -r requirements.txt && \
      python3 backend/"ecommerce project"/project/manage.py migrate && \
      python3 backend/"ecommerce project"/project/manage.py collectstatic --noinput
    startCommand: gunicorn project.wsgi:application --chdir backend/"ecommerce project"/project --bind 0.0.0.0:$PORT
