services:
  - type: web
    name: django-backend
    env: python
    rootDir: backend/ecommerce/project   # 👈 very important
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn project.wsgi:application --preload
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-app.onrender.com,localhost,127.0.0.1
