services:
  - type: web
    name: ecommerce
    env: python
    buildCommand: pip install -r backend/ecommerce/requirements.txt && cd backend/ecommerce && python manage.py collectstatic --noinput
    startCommand: cd backend/ecommerce && gunicorn project.project.wsgi:application

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-app.onrender.com,localhost,127.0.0.1
