services:
  - type: web
    name: ecommerce-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python3 backend/ecommerce/manage.py migrate
      python3 backend/ecommerce/manage.py collectstatic --noinput
    startCommand: gunicorn backend.ecommerce.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "ecommerce-app.onrender.com"
