services:
  - services:
  - type: web
    name: ecommerce
    env: python
    buildCommand: cd backend/ecommerce && python manage.py collectstatic --noinput
    startCommand: cd backend/ecommerce && gunicorn project.wsgi

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-app.onrender.com,localhost,127.0.0.1
