services:
  - type: web
    name: ecommerce-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python backend/ecommerce/project/manage.py migrate
      python backend/ecommerce/project/manage.py collectstatic --noinput
    startCommand: gunicorn backend.ecommerce.project.wsgi:application --bind 0.0.0.0:$PORT
