services:
  - type: web
    name: ecommerce
    env: python
    buildCommand: cd backend && pip install -r ecommerce/requirements.txt && python ecommerce/manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn ecommerce.project.project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-app.onrender.com,localhost,127.0.0.1
