services:
  - type: web
    name: django-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python backend/ecommerce/project/manage.py collectstatic --noinput
    startCommand: gunicorn project.wsgi:application --chdir backend/ecommerce/project --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
