services:
  - type: web
    name: ecommerce
    env: python
    buildCommand: pip install --upgrade pip && pip install -r backend/ecommerce/requirements.txt && python backend/ecommerce/manage.py migrate --noinput && python backend/ecommerce/manage.py collectstatic --noinput

    startCommand: gunicorn project.wsgi:application --chdir backend/ecommerce --timeout 90

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: majorproject1-ecommerce-cart.onrender.com,localhost,127.0.0.1
