services:
  - type: web
    name: ecommerce-django
    env: python
    plan: free        # or "starter", "standard" etc. depending on your plan
    region: oregon    # or "frankfurt", "singapore" etc.
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python backend/ecommerce_project/project/manage.py migrate --noinput
      python backend/ecommerce_project/project/manage.py collectstatic --noinput
    startCommand: |
      gunicorn project.wsgi:application --chdir backend/ecommerce_project/project --bind 0.0.0.0:$PORT
    autoDeploy: true
