services:
  - type: web
    name: django-backend
    env: python
    plan: free
    workingDirectory: backend/ecommerce/project
    buildCommand: |
      pip install -r ../../requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn project.wsgi:application --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: WEB_CONCURRENCY
        value: 4
